version: '3.7'
services:

  postgres:
    # oimage: sisedgar/dbprueba2:1.1
    image: sisedgar/midocker:1.1
    container_name: postgres11
    restart: always
    volumes:
      - ../data:/var/lib/postgresql/data
    ports:
      - 5430:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin" 
    ports:
      - "100:80"
    depends_on:
      - postgres


volumes:
  data: {}
